USE DATABASE {{env_vars.SF_DATABASE_RAW}};
USE SCHEMA {{env_vars.SF_SCHEMA_SALESFORCE}};

ALTER SESSION SET QUERY_TAG = 'TEST_SCHEMA_CHANGE_DEPLOY';


CREATE TABLE TEST_TABLE_100
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);


CREATE TABLE TEST_TABLE_101
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

