USE DATABASE {{env_vars.SF_DATABASE_RAW}};
USE SCHEMA {{env_vars.SF_SCHEMA_SALESFORCE}};

CREATE OR REPLACE TABLE {{env_vars.SF_DATABASE_RAW}}.{{env_vars.SF_SCHEMA_SALESFORCE}}.TEST_TABLE_TBL2
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);