USE DATABASE {{env_vars.SF_DATABASE_RAW}};
USE SCHEMA {{env_vars.SF_SCHEMA_SALESFORCE}};

-- ALTER SESSION SET QUERY_TAG = 'V3.1.9__prd create test TABLES';


CREATE OR REPLACE TABLE {{env_vars.SF_DATABASE_RAW}}.{{env_vars.SF_SCHEMA_SALESFORCE}}.TEST_TABLE_100
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);


CREATE OR REPLACE TABLE {{env_vars.SF_DATABASE_RAW}}.{{env_vars.SF_SCHEMA_SALESFORCE}}.TEST_TABLE_101
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

CREATE OR REPLACE VIEW {{env_vars.SF_DATABASE_RAW}}.{{env_vars.SF_SCHEMA_SALESFORCE}}.TEST_TABLE_VW AS 
SELECT A.FIRST_NAME FROM {{env_vars.SF_DATABASE_RAW}}.{{env_vars.SF_SCHEMA_SALESFORCE}}.TEST_TABLE_100 A, 
{{env_vars.SF_DATABASE_RAW}}.{{env_vars.SF_SCHEMA_SALESFORCE}}.TEST_TABLE_101 B 
WHERE A.FIRST_NAME = B.FIRST_NAME;

