USE DATABASE {{env_vars.SF_DATABASE_RAW}};
USE SCHEMA {{env_vars.SF_SCHEMA_SALESFORCE}};

-- ALTER SESSION SET QUERY_TAG = 'V3.1.9__prd create test TABLES';


CREATE OR REPLACE TABLE {{env_vars.SF_DATABASE_RAW}}.{{env_vars.SF_SCHEMA_SALESFORCE}}.TEST_TABLE_10001
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

